services:
  etcd0: &etcd-base
    image: quay.io/coreos/etcd:v3.5.18
    entrypoint: /usr/local/bin/etcd
    networks:
      - patroni
    restart: always
    command:
      - --name=etcd0
      - --data-dir=/etcd-data
      - --initial-advertise-peer-urls=http://etcd0:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd0:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380
      - --initial-cluster-state=new
      - --enable-v2=true
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256m

  etcd1:
    <<: *etcd-base
    command:
      - --name=etcd1
      - --data-dir=/etcd-data
      - --initial-advertise-peer-urls=http://etcd1:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd1:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380
      - --enable-v2=true

  etcd2:
    <<: *etcd-base
    command:
      - --name=etcd2
      - --data-dir=/etcd-data
      - --initial-advertise-peer-urls=http://etcd2:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd2:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380
      - --enable-v2=true
  etcd3:
    <<: *etcd-base
    command:
      - --name=etcd3
      - --data-dir=/etcd-data
      - --initial-advertise-peer-urls=http://etcd3:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd3:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380
      - --enable-v2=true
  etcd4:
    <<: *etcd-base
    command:
      - --name=etcd4
      - --data-dir=/etcd-data
      - --initial-advertise-peer-urls=http://etcd4:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://etcd4:2379
      - --listen-client-urls=http://0.0.0.0:2379
      - --initial-cluster=etcd0=http://etcd0:2380,etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380,etcd4=http://etcd4:2380
      - --enable-v2=true

  patroni0: &patroni-base
    build: patroni
    entrypoint: [/bin/sh, /entrypoint.sh]
    restart: always
    volumes:
      - ./patroni.yml:/patroni.yml:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    environment:
      PATRONI_API_CONNECT_PORT: 8008
      REPLICATION_NAME: slave
      REPLICATION_PASS: slave
      SU_NAME: postgres
      SU_PASS: supass
      POSTGRES_APP_ROLE_PASS: appass
    networks:
      - patroni
    depends_on:
      - etcd0
      - etcd1
      - etcd2
      - etcd3
      - etcd4
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512m

  patroni1:
    <<: *patroni-base
  patroni2:
    <<: *patroni-base
  patroni3:
    <<: *patroni-base
  patroni4:
    <<: *patroni-base

  haproxy:
    image: haproxy:3.1.3-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - 5432:5432
      - 5433:5433
      - 8080:8080
    restart: always
    networks:
      - patroni
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 64m

networks:
  patroni:
    driver: bridge
